[profile.default]
src = './'
out = 'out'
libs = ['lib']
test = 'test'
solc_version = '0.8.24'
auto_detect_remappings = false
remappings = [
    '@openzeppelin/=lib/openzeppelin/',
    '@uniswap/v2-periphery/=test/helpers',
    'forge-std/=lib/forge-std/src/'
]